
[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[build.environment]
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"




[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
